### ISSUE TITLE
Segmentation fault Day8 deisjointset

### ISSUE THREAD

**Issue by hardikhere** [hardikhere/100-days-of-Algo#1]
I am unable to figureout why im getting segmentaion fault in disjoint set Day8

**Comment by hardikhere** [comment]
@varuogm  @chandresh189 can you help me plox

**Comment by abraham-john-paul** [comment]
HI can i work on this

**Comment by abraham-john-paul** [comment]
`void Graph::addEdge(int u, int v){
    adj[u].push_back(v);
}`
problem is here

**Comment by hardik-here** [comment]
Sure go ahead

**Comment by chandresh189** [comment]
i did not studied disjoint set, thanks @abraham-john-paul

**Comment by abraham-john-paul** [comment]
What are you trying to achieve in this pgm?

**Comment by hardik-here** [comment]
> What are you trying to achieve in this pgm?

This is a program to check is graph contains cycle or not. Using disjoint sets.

**Comment by hardik-here** [comment]
> What are you trying to achieve in this pgm?

This is a program to check if graph contains cycle or not using disjoint sets

**Comment by abraham-john-paul** [comment]
The  problem is the usage of vectors like this, you are trying to access indices that aren't there.
You can assign this to someone else :+1:

**Comment by varuogm** [comment]
where can i access the code.its not visible

**Comment by hardikhere** [comment]
> The problem is the usage of vectors like this, you are trying to access indices that aren't there.
> You can assign this to someone else

no problem john I will fix that tonight thanks :+1:

**Comment by hardikhere** [comment]
> where can i access the code.its not visible

Just look at the Day8 cpp file
