### ISSUE TITLE
add comments in program to help learners understand better

### ISSUE THREAD

**Issue by hardikhere** [hardikhere/100-days-of-Algo#12]

**Comment by je117er** [comment]
Can you assign this issue to me?

**Comment by Codedude1** [comment]
Is this issue open? I would like to contribute.

**Comment by aditya576** [comment]
Hey,I would like to work on this. Can you assign me for this issue?

**Comment by satthi153** [comment]
Hi, I would like to contribute.

**Comment by hardikhere** [comment]
Yeah guys go ahead. It's open

**Comment by namratadas1** [comment]
May I work on this issue?
