### ISSUE TITLE
Add additional algorithms topics wise

### ISSUE THREAD

**Issue by hardikhere** [hardikhere/100-days-of-Algo#5]

**Comment by saiharsha-22** [comment]
@hardikhere  Hi I would like to contribute binary search algorithms in java programming, can I?

**Comment by pranjanpr** [comment]
I am new to open source. I can add heapsort algorithm in C++. @hardikhere please tell me more.

**Comment by hardikhere** [comment]
> @hardikhere Hi I would like to contribute binary search algorithms in java programming, can I?

Yeah go ahead make a folder name Search Algorithms and add that in.

**Comment by hardikhere** [comment]
> I am new to open source. I can add heapsort algorithm in C++. @hardikhere please tell me more.

Heap sort is already in sorting folder, You may add any other sort algo. Thanks

**Comment by pranjanpr** [comment]
@hardikhere so I can add selection sort and radix sort. Is it fine?

**Comment by saiharsha-22** [comment]
@hardikhere Thank u , I will do my task

**Comment by Jainchhavi16** [comment]
Can I add graph coloring problem in graph algo folder?

**Comment by vortex2099** [comment]
Can I add the Big Integer problem?

**Comment by saiharsha-22** [comment]
@hardikhere I have added The Binary search folder successfully and sent a pull request can you please check once.

![Screenshot (390)](https://user-images.githubusercontent.com/61947484/94794614-c0201480-03f9-11eb-8780-ad7a9c450bab.png)

**Comment by hardikhere** [comment]
> @hardikhere I have added The Binary search folder successfully and sent a pull request can you please check once.
> 
> ![Screenshot (390)](https://user-images.githubusercontent.com/61947484/94794614-c0201480-03f9-11eb-8780-ad7a9c450bab.png)

Yeah I acknoledged you contribution :) thanks will merge that soon

**Comment by hardikhere** [comment]
> Hey !! Can i add insertion and counting sort algo in c++

Yeah go ahead

**Comment by snehagupta-4** [comment]
@hardikhere Hey, can I add scheduling algorithms in c++?

**Comment by Riya-code** [comment]
@hardikhere Hey, Can I add Bucket Sort algorithm in cpp?

**Comment by anirudh2019** [comment]
@hardikhere Hi, Can I add Gnome Sort algo in C++?

**Comment by darshancool25** [comment]
@hardikhere Can i contribute to Graph Algorithms ? I can add algo to find Articulation points in a graph
