### ISSUE TITLE
Add practise problems topic wise

### ISSUE THREAD

**Issue by hardikhere** [hardikhere/100-days-of-Algo#6]
Create folder named [PRACTISE_TOPIC-NAME] and add problems and solutions in that. please add problem link also or create seprate readmefile for that. :)
Happy contribution :+1:

**Comment by satwik-chowdary** [comment]
I can do this, but how many problems to be added

**Comment by poojitha2002** [comment]
I would like to contribute

**Comment by Jainchhavi16** [comment]
I would like to work on this issue.
Please assign this issue to me.

**Comment by Pranjal81** [comment]
I would love to work on that idea, please assign this to me.

**Comment by hardikhere** [comment]
> I can do this, but how many problems to be added

As much you want, Thanks for contributing :+1:

**Comment by hardikhere** [comment]
> I would like to work on this issue.
> Please assign this issue to me.

Yeah go ahead

**Comment by hardikhere** [comment]
> I would love to work on that idea, please assign this to me.

Assigned. Thanks

**Comment by poojitha2002** [comment]
I would like to work on this issue.
Please assign this issue to me.

**Comment by sagunjaiswal** [comment]
I would love to work on that idea, please assign this.

**Comment by Mohit123singh** [comment]
hi,I would like to work on this can u please assign this to me?

**Comment by jainaayush01** [comment]
hey @hardik-here I would like to add some practice problems on Sliding Window Algorithm from Leetcode.
Problems are of Medium Difficulty:
https://leetcode.com/problems/permutation-in-string/
https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/
If you liked my idea than let me know i will make the pull request accordingly.
Thanks

**Comment by hardikhere** [comment]
> hey @hardik-here I would like to add some practice problems on Sliding Window Algorithm from Leetcode.
> Problems are of Medium Difficulty:
> https://leetcode.com/problems/permutation-in-string/
> https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/
> If you liked my idea than let me know i will make the pull request accordingly.
> Thanks

Go ahead ayush create a pr thanks

**Comment by guptaa98** [comment]
I would like to work on this!

**Comment by eshasachan18** [comment]
> Create folder named [PRACTISE_TOPIC-NAME] and add problems and solutions in that. please add problem link also or create seprate readmefile for that. :)
> Happy contribution 👍

I want to work on this

**Comment by sammanchanchal** [comment]
I have added a max. sum of adjacent numbers program in dynamic programming section and sent you the pull request for the same.

**Comment by Anshul275** [comment]
@hardikhere I would like to contribute on Dynamic Programming - Shortest Common Supersequence Problem.
Problem Statement - Given two strings str1 & str2, find the shortest possible string that has both str1 and str2 as subsequences. Also print the shortest possible string. 

Can i go for it??
