### ISSUE TITLE
Accepted PRs don't have tag that says hacktoberfest-accepted

### ISSUE THREAD

**Issue by pranav230** [hardikhere/100-days-of-Algo#90]
![Screenshot from 2020-10-07 16-05-10](https://user-images.githubusercontent.com/37182018/95320446-1936ef00-08b7-11eb-947e-ba14d217b41b.png)
According to Hacktoberfest rules for valid PRs. The accepted PR must have a tag hacktoberfest-accepted.
`https://hacktoberfest.digitalocean.com/hacktoberfest-update`

**Comment by hardikhere** [comment]
There is OR between the rules read, Either PR has a label "hacktoberfest-accepted" by maintainer OR {
repo has hacktoberfest labelled and pr merged
}
we are done with 2nd option given by them, ask them if they can help
